export { default as auth } from "./auth";
export { default as notification } from "./notification";
export { default as trade } from "./trade";
export { default as deals } from "./deals";
export { default as user } from "./user";
export { default as withdrawal } from "./withdrawal";
export { default as verify } from "./verify";
export { default as admin } from "./admin";
export { default as referral } from './referral';
export { default as promocodes } from './promocodes';
export { default as settings } from './settings'
export { default as deposit } from './deposit'